name: Daily Traffic Pull

on: 
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ETL Steps
        env:
          TRAFFIC_API_KEY: ${{ secrets.TRAFFIC_API_KEY }}
        run: |
          cd auto-traffic-etl
          python extract_data.py
          python transform_data.py
          python load_to_bigquery.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt



  
